remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "//lingard.github.io/fp-ts-wonka/"
  "GitHub":
    - "//github.com/lingard/fp-ts-wonka"
